version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: chmod +x ./mvnw
      - run: ./mvnw clean install

  test_general:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: chmod +x ./mvnw
      - run: ./mvnw test -Dtest=SpringBootBackendApirestApplicationTests

  test_service:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: chmod +x ./mvnw
      - run: ./mvnw test -Dtest=ClienteServiceImplTest

  package:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: chmod +x ./mvnw
      - run: ./mvnw clean package

  dependency-check:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run: chmod +x ./mvnw
      - run: ./mvnw org.owasp:dependency-check-maven:check

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_general:
          requires:
            - build
      - test_service:
          requires:
            - build
      - package:
          requires:
            - test_general
            - test_service
      - dependency-check:
          requires:
            - build
